### ISSUE TITLE
Row Start and Row Stop parameters in scanning a hbase table

### ISSUE THREAD

**Issue by venkat9yash** [nkeyes/ok_hbase#11]
Hi,

I tried to implement row_start and row_stop parameters in scanning hbase table using the ok_hbase gem. It seems like its ignoring the filter and giving me all the data that is available in the table. Can you please help me regarding this?

```
table.scan(row_start:'2013-08-29 12:30:00', row_stop:'2013-08-29 13:00:00') do |row_key, columns|
```

Thanking You,
Yash Gunapati

**Comment by nkeyes** [comment]
Hey. I'll look into this as soon as I can.

**Comment by venkat9yash** [comment]
Thanks a lot

**Comment by nkeyes** [comment]
@venkat9yash the example you provide is using the wrong option names.
You want `start_row` and `stop_row`, not `row_start` and `row_stop`.

It should be:

``` ruby
table.scan(start_row: '2013-08-29 12:30:00', stop_row: '2013-08-29 13:00:00') do |row_key, columns|
  # do stuff...
end
```

Try that and let me know if you are still having an issue.

**Comment by venkat9yash** [comment]
It worked with the alteration, Thanks a lot for the help. I assumed row_start from the row_prefix parameter in the example.

**Comment by nkeyes** [comment]
No problem, sorry for the confusion.
I've updated the readme with examples.
