### ISSUE TITLE
Using Filters in Row Scan

### ISSUE THREAD

**Issue by venkat9yash** [nkeyes/ok_hbase#12]
Hi,

I am trying to use filters in table scan with ok_hbase gem. As, i didn't find an example i  used similar syntax to one i used in python

Python Syntax:

for key, data in table.scan(row_start='2013-08-29 12:30:00', row_stop='2013-08-29 13:00:00',columns={'Solectria'},filter="ColumnPrefixFilter('Inv1')"):

But when i implement similar idea in ruby, It doesn't seem to work

OK_Hbase Implementation:

 table.scan(start_row: '2013-08-29 13:00:00',stop_row: '2013-08-29 13:30:00', columns:['Solectria'], filter: { ColumnPrefixFilter: 'Inv1' })

Can you please help me regarding this?

Thanking You,
Yash Gunapati

**Comment by nkeyes** [comment]
Currently, filter support is a bit cumbersome in ok_hbase.
you want to use the `filter_string` option with your scan and pass in a string following the rules in the [Hbase Thrift docs](http://hbase.apache.org/book/thrift.html). Check out section 10.3.1.8 for examples.
I think some of the documentation there is slightly wrong, so you might want to refer to the [JavaDocs](http://hbase.apache.org/apidocs/org/apache/hadoop/hbase/filter/FilterBase.html), specifically, the constructor signatures for the sub-classes of `FilterBase` 

So, for your case, you would want:

``` Ruby
table.scan(
  start_row: '2013-08-29 13:00:00',
  stop_row: '2013-08-29 13:30:00',
  columns: ['Solectria'],
  filter_string: "ColumnPrefixFilter('Inv1')"
)
```

**Comment by venkat9yash** [comment]
Thanks a lot, This works perfectly fine. Can i use all the other filters in the similar fashion ?

**Comment by nkeyes** [comment]
Yeah, I believe you should be able to use any filter supported by your version of HBase; its just a string thats passed through.
