### ISSUE TITLE
Can i pull meta data using OK_Hbase gem

### ISSUE THREAD

**Issue by venkat9yash** [nkeyes/ok_hbase#14]
I am trying to pull in all the columnfamily names and column names available through OK_Hbase gem, is it possible through the current version?

**Comment by nkeyes** [comment]
HBase is schemaless, each row can have different fields. To get every column name, you'd literally have to scan every row. This is a very bad idea considering the aount of data HBase is meant to handle.

To get a list of column family names you can use:
[`OkHbase::Concerns::Table#families`](https://github.com/nkeyes/ok_hbase/blob/master/lib/ok_hbase/concerns/table.rb#L39)

``` ruby
# get a connection
conn = OkHbase::Connection.new(
  host: 'localhost',
  port: 9090,
  auto_connect: true
)

# get an instance of OkHbase::Table tied to an existing table
table = OkHbase::Table.new('ok_hbase_test', conn)

table.families.keys
```

**Comment by venkat9yash** [comment]
Thanks for the information Nathan.

**Comment by venkat9yash** [comment]
Another question, i had with ColumnPrefixFilter was, if my column names have Inv1_AC_POWER and Inv2_AC_POWER. can i use AC_POWER to filter values out instead of specifying the the complete name. Something like *_AC_POWER.

I would be really grateful for the solution, this will work well with my thesis.

**Comment by nkeyes** [comment]
[ColumnPrefixFilter](http://hbase.apache.org/0.94/apidocs/org/apache/hadoop/hbase/filter/ColumnPrefixFilter.html) filters on the beginning of the names of columns, not the ends. So, your column names would have to be AC_POWER_Inv1, AC_POWER_Inv2, etc.

With your existing column names, i think you want [QualifierFilter](http://hbase.apache.org/0.94/apidocs/org/apache/hadoop/hbase/filter/QualifierFilter.html) using a [SubstringComparator](http://hbase.apache.org/0.94/apidocs/org/apache/hadoop/hbase/filter/SubstringComparator.html) or maybe [RegexStringComparator](http://hbase.apache.org/0.94/apidocs/org/apache/hadoop/hbase/filter/RegexStringComparator.html)
