### ISSUE TITLE
Connection to Remote Hbase

### ISSUE THREAD

**Issue by fion8828** [nkeyes/ok_hbase#2]
Hi All, 

I'm relatively new to Hbase and the gem that connects to Hbase.
Currently I have a hadoop cluster set up remotely, but ruby on rails is on my local laptop. 
My question is how to use ok-hbase to connect to hbase on remote server? I know the IP address for the server and the port number for the Thrift server on it. 
Just want to make the connect work. 

Thanks, 

Fiona

**Comment by nkeyes** [comment]
Hey Fiona,
Sorry for the lack of documentation and examples, this is still a very new project.

Here's a simple example on how to connect and get some data

``` ruby
# get connection
conn = OkHbase::Connection.new({
  auto_connect: true,
  host: your_hbase_thrift_host,
  port: your_hbase_thrift_port,
  timeout: some_int_number_of_seconds
})

# get table
table = OkHbase::Table.new('your_table_name', conn)

# get all records with row_keys starting with 'a'
table.scan(row_prefix: 'a') do |row_key, columns|
 # do something with row_rey and/or columns
end
```

If you're looking for a more Rails-ish/ActiveRecord way of doing things, thats possible (we actually do that here at Labs), but an example like that is more involved. I'm home sick today, but if you want a more Rails-like example, I can probably put something together in the next couple days.

Good luck,
Nathan

**Comment by kmcminn** [comment]
take a look at examles/perf_read*, the write ones aren't quite finished.

**Comment by fion8828** [comment]
Thanks a lot! My team are counting on your gem, since there's not lot
available gems to use.

2013/6/10 Nathan Keyes notifications@github.com

**Comment by fion8828** [comment]
Hi Nathan & kmcminn, 

I took perf_read\* as an example, and add connection variables to this file:
$options[:hostname] = "localhost"
$options[:table] = "test"
$options[:filter_array] = "array"
$options[:filter_pack] = "tes"
$options[:port] = 9090

Saved the changes and type : bundle exec ruby perf_read.rb test in terminal. 
I got error like this:
Emergings-MacBook-Air-2:examples ETLuser$ bundle exec ruby perf_read.rb test
/Users/ETLuser/ok-hbase/vendor/ruby/1.9.1/gems/thrift-0.9.0/lib/thrift/transport/socket.rb:54:in `rescue in open': Could not connect to localhost:9090: Invalid argument - connect(2) (Thrift::TransportException)
    from /Users/ETLuser/ok-hbase/vendor/ruby/1.9.1/gems/thrift-0.9.0/lib/thrift/transport/socket.rb:36:in`open'
    from /Users/ETLuser/ok-hbase/vendor/ruby/1.9.1/gems/thrift-0.9.0/lib/thrift/transport/buffered_transport.rb:37:in `open'
    from /Users/ETLuser/ok-hbase/lib/ok_hbase/connection.rb:58:in`open'
    from /Users/ETLuser/ok-hbase/lib/ok_hbase/connection.rb:52:in `initialize'
    from perf_read.rb:37:in`new'
    from perf_read.rb:37:in `get_connection'
    from perf_read.rb:73:in`perf_test_b'
    from perf_read.rb:148:in `main'
    from perf_read.rb:151:in`<main>'

Can anyone tell me what's wrong in connection?

Thanks, 

Fiona

**Comment by nkeyes** [comment]
Do you have thrift running locally as well as HBase?
If you're on a Mac and installed HBase with brew, you should just be able to do this from the command line:

``` bash
hbase thrift start -threadpool
```

**Comment by vmeng** [comment]
Hi nkeyes:

I already connect the HBase table. I follow the http://hbase.apache.org/book/quickstart.html to create the table.

$test_table = OkHbase::Table.new('test', conn)

$test_table.scan(row_prefix: 'a') do |row_key, columns|
 # do something with row_rey and/or columns
end

I am new rubyer and i think i did not get the correct usage of $test_table.scan, can you show me how to use?
BTW, the example seams not correct in perf_read.rb for get_row_count(conn, prefix)

Thanks.

**Comment by nkeyes** [comment]
I have put together a quick, hopefully simpler example.
see: https://github.com/okcwest/ok-hbase/tree/master/examples

**Comment by nkeyes** [comment]
Does that give you what you need?

**Comment by fion8828** [comment]
Nathan, 

Thanks for putting those info together. Yes, The connection to Thrift Server works. Now we try to hard code the options, like IP, port, instead of parsing options from command line. I appreciate your help. 

Fiona

**Comment by nkeyes** [comment]
No problem, glad to help!

**Comment by nkeyes** [comment]
If you're at HBaseCon today, and would like to meet, I'm here too.

**Comment by vmeng** [comment]
Thank you nkeyes.
I can read and write now. The ok_hbase gem is very easy to use. I can't read table before is because the thrift server not support Ruby since i install via source code. After change to use hbase commend ([hbase-root]/bin/hbase thrift start) to open thrift server , it works.

**Comment by gummoe** [comment]
Are you able to provide more information on the "Rails-ish/ActiveRecord way of doing things". I'd like to be able to maintain my Thrift connection instead of needing to open a new one for each time I process a request through my controller. 

I've created a global connection variable for an instance of OkHbase::Connection as a work-around, but that obviously isn't ideal. 

Still, thank you so much for developing this gem. It is WAY easier to work with than massive_record, which doesn't play nice with newer versions of ruby and rails.
