### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by kknono** [nkeyes/ok_hbase#3]
Hi nkeyes,
I have no idea how to run these examples, could you please show me the detail steps to run an example successfully in terminal?  

thanks.

**Comment by nkeyes** [comment]
I have put together a quick, hopefully simpler example.
see: https://github.com/okcwest/ok-hbase/tree/master/examples

**Comment by nkeyes** [comment]
Does that give you what you need?

**Comment by kknono** [comment]
OK, that is what I want. Thanks very much.

**Comment by nkeyes** [comment]
Great, glad to help.

**Comment by nkeyes** [comment]
If you're at HBaseCon today, and would like to meet, I'm here too.
