### ISSUE TITLE
Upgrade hbase.rb to latest Thrift interface definition file

### ISSUE THREAD

**Issue by bigsur0** [nkeyes/ok_hbase#7]
Do you have any plans to upgrade the Thrift client in the lib/thrift? There are new methods and signatures that I think would be great to have incorporated. For instance, the batch #incrementRows method.

http://svn.apache.org/viewvc/hbase/tags/0.95.2/hbase-server/src/main/resources/org/apache/hadoop/hbase/thrift/Hbase.thrift?view=markup

**Comment by nkeyes** [comment]
Hey, i'll take a look at it this weekend.
